// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obidalar.Data;

#nullable disable

namespace Obidalar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430113842_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obidalar.Models.Obida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RasmUrl")
                        .HasColumnType("text");

                    b.Property<string>("Tavsif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Viloyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Obidalar");
                });

            modelBuilder.Entity("Obidalar.Models.Sharh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Matn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObidaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ObidaId");

                    b.ToTable("Sharhlar");
                });

            modelBuilder.Entity("Obidalar.Models.Sharh", b =>
                {
                    b.HasOne("Obidalar.Models.Obida", "Obida")
                        .WithMany("Sharhlar")
                        .HasForeignKey("ObidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obida");
                });

            modelBuilder.Entity("Obidalar.Models.Obida", b =>
                {
                    b.Navigation("Sharhlar");
                });
#pragma warning restore 612, 618
        }
    }
}
